general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
}

# Listener 1: Lock screen after 5 minutes (300s)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Listener 2: Turn off screen (save battery) after 5.5 minutes
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Listener 3: Suspend (Deep Sleep) after 10 minutes
listener {
    timeout = 600
    on-timeout = systemctl suspend
}
